### ISSUE TITLE
How to avoid updating PDF attachments

### ISSUE THREAD

**Issue by BerginJay** [gaoyu19920914/zoteroMetadataUpdater#1]
Executing this javascript code will generate a new temporary item, and the generated item contains an automatically obtained pdf attachment. How to avoid automatically obtaining the pdf attachment of this temporary item?

**Comment by gaoyu19920914** [comment]
> Executing this javascript code will generate a new temporary item, and the generated item contains an automatically obtained pdf attachment. How to avoid automatically obtaining the pdf attachment of this temporary item?

@BerginJay ,
Thanks for pointing this out! I didn't notice this. Just checked using 2 entries (research articles with Open Access) with only DOI, and the script **DO** creates a new folder under my C:\Users\USERNAME\Zotero\storage\ with one PDF attachment.

However, there's no [public zotero JS api](https://www.zotero.org/support/dev/client_coding/javascript_api) to delete files, and Dan Stillman replied [here](https://groups.google.com/g/zotero-dev/c/cU-6O8cCWsg/m/X7y_7nS9BAAJ) concerning file operations.

If you do mind this, you can delete the latest folder in your zotero storage. Manually removing the most recent folder doesn't seem to be harmful to the zotero library.

**Comment by BerginJay** [comment]
Thanks for your reply! As this is not possible, I'm going to close this issue.
